name: macos

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: macOS-latest

    strategy:
      matrix:
        include:
          - perl: /usr/bin/perl
            prove: /usr/bin/prove
            cpm-option: --sudo
          - perl: /usr/local/bin/perl
            prove: /usr/local/bin/prove
            cpm-option: ''

    name: perl (${{ matrix.perl }})

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: ${{ matrix.perl }} -V
      - name: Install Dependencies
        run: curl -fsSL --compressed https://git.io/cpm | ${{ matrix.perl }} - install -g ${{ matrix.cpm-option }} --with-develop --with-recommends --show-build-log-on-failure
      - name: Run Tests
        run: ${{ matrix.prove }} -lr t xt
